# Use an official Ruby runtime as the base image
FROM ruby:2.7

# Set the working directory in the container
WORKDIR /app

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Install gems
RUN bundle install

# Copy the rest of your application code into the container
COPY . .

# Install Rails and other dependencies
RUN gem install rails

# Copy the rest of the application code into the container
COPY ..

# Expose port 3000 (the default Rails server port)
EXPOSE 3000

# Start the Rails application
CMD ["rails", "server", "-b", "0.0.0.0"]
